### ISSUE TITLE
css-loader 4.x.x support?

### ISSUE THREAD

**Issue by Sombian** [vuejs/vue-style-loader#46]
vue-loader stopped working after upgrade css-loader to 4.x.x from 3.6.0.
i see some breaking changes documented on css-loader repo.
please fix this.

**Comment by huangkaiqiao** [comment]
I have encountered the same problem as you do.
i can't find out what's wrong with webpack.config.js of my project 
until open this issue.
plz fix this. or change official document of vue-loader.
thanks a lot.

**Comment by foxxyz** [comment]
@huangkaiqiao for most purposes you can safely swap out `vue-style-loader` with `style-loader` and your project should work fine. Also see #42 

I will look into what exactly is causing the problem...

**Edit:** the problem is that [`css-loader`'s `esModule` option](https://github.com/webpack-contrib/css-loader#esmodule) is [set to `true` by default in v4](https://github.com/webpack-contrib/css-loader/releases/tag/v4.0.0). The correct workaround for now is replacing the `css-loader` declaration in your webpack config with:

```
{
    loader: 'css-loader',
    options: {
        esModule: false
    }
}
```

**Comment by nofacer** [comment]
@foxxyz works for me. Thanks a lot.

**Comment by IAmJulianAcosta** [comment]
Confirmed, @foxxyz solution worked

**Comment by privatenumber** [comment]
Minimal reproduction repo for reference: https://github.com/privatenumber/vue-css-loader-bug

**Comment by ccnixon** [comment]
I was stuck on this issue for days. @foxxyz solution worked for me.

**Comment by Otto-J** [comment]
耗费了好久时间来排查这个问题。希望更新文档

**Comment by p2yang** [comment]
Thanks. It's ok to use `style-loader@2` to replace `vue-style-loader`.
